spring:
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;
    username: admin
    password:

  servlet:
      multipart:
          max-file-size: 10MB

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
